import type { Question } from "./mockData";

// Additional questions appended to each subject's bank.
// Kept in declaration order — exams serve them sequentially after the originals.
export const extraQuestions: Record<string, Question[]> = {
  mathematics: [
    { id: "math-21", question: "What is 25% of 80?", options: ["15", "20", "25", "30"], correctAnswer: 1, explanation: "25/100 × 80 = 20." },
    { id: "math-22", question: "Solve: x/3 = 9", options: ["18", "21", "27", "30"], correctAnswer: 2, explanation: "x = 9 × 3 = 27." },
    { id: "math-23", question: "What is 9 × 12?", options: ["96", "108", "112", "120"], correctAnswer: 1, explanation: "9 × 12 = 108." },
    { id: "math-24", question: "Cube root of 125?", options: ["4", "5", "6", "25"], correctAnswer: 1, explanation: "5³ = 125." },
    { id: "math-25", question: "Area of a triangle base 10cm, height 6cm?", options: ["16 cm²", "30 cm²", "60 cm²", "120 cm²"], correctAnswer: 1, explanation: "½ × 10 × 6 = 30." },
    { id: "math-26", question: "Convert 2/5 to a percentage.", options: ["20%", "25%", "40%", "50%"], correctAnswer: 2, explanation: "2/5 = 0.4 = 40%." },
    { id: "math-27", question: "Solve: 4x − 3 = 17", options: ["3", "4", "5", "6"], correctAnswer: 2, explanation: "4x = 20, x = 5." },
    { id: "math-28", question: "Sum of angles on a straight line?", options: ["90°", "120°", "180°", "360°"], correctAnswer: 2, explanation: "Straight line = 180°." },
    { id: "math-29", question: "What is 0.2 × 0.5?", options: ["0.01", "0.1", "1.0", "0.25"], correctAnswer: 1, explanation: "0.2 × 0.5 = 0.10." },
    { id: "math-30", question: "Ratio simplified: 12 : 18", options: ["1:2", "2:3", "3:4", "4:6"], correctAnswer: 1, explanation: "Divide by 6 → 2:3." },
    { id: "math-31", question: "Perimeter of rectangle 7cm × 4cm?", options: ["11 cm", "22 cm", "28 cm", "44 cm"], correctAnswer: 1, explanation: "2(7+4) = 22 cm." },
    { id: "math-32", question: "Mean of 4, 8, 12, 16?", options: ["8", "10", "12", "14"], correctAnswer: 1, explanation: "40/4 = 10." },
    { id: "math-33", question: "What is 3⁴?", options: ["12", "27", "64", "81"], correctAnswer: 3, explanation: "3×3×3×3 = 81." },
    { id: "math-34", question: "Solve: 2(x + 3) = 14", options: ["3", "4", "5", "7"], correctAnswer: 1, explanation: "x + 3 = 7, x = 4." },
    { id: "math-35", question: "Number of sides in a hexagon?", options: ["4", "5", "6", "8"], correctAnswer: 2, explanation: "Hexagon has 6 sides." },
    { id: "math-36", question: "Median of 3, 5, 9, 11, 15?", options: ["5", "9", "11", "8.6"], correctAnswer: 1, explanation: "Middle value is 9." },
    { id: "math-37", question: "Convert 1.5 hours to minutes.", options: ["60", "75", "90", "120"], correctAnswer: 2, explanation: "1.5 × 60 = 90 min." },
    { id: "math-38", question: "Simplify: 15/25", options: ["2/5", "3/5", "1/2", "3/4"], correctAnswer: 1, explanation: "Divide by 5 → 3/5." },
    { id: "math-39", question: "What is 100 − 37?", options: ["53", "63", "67", "73"], correctAnswer: 1, explanation: "100 − 37 = 63." },
    { id: "math-40", question: "Area of a circle r=7 (π=22/7)?", options: ["44", "100", "144", "154"], correctAnswer: 3, explanation: "πr² = 22/7 × 49 = 154." },
  ],

  english: [
    { id: "eng-21", question: "Plural of 'mouse' (animal)?", options: ["Mouses", "Mice", "Mices", "Mouse"], correctAnswer: 1, explanation: "Irregular plural: mice." },
    { id: "eng-22", question: "Past tense of 'write'?", options: ["Writed", "Wrote", "Written", "Writing"], correctAnswer: 1, explanation: "Simple past: wrote." },
    { id: "eng-23", question: "Synonym of 'big'?", options: ["Small", "Large", "Tiny", "Short"], correctAnswer: 1, explanation: "Big = large." },
    { id: "eng-24", question: "Choose correct: 'There ___ five apples.'", options: ["is", "are", "was", "be"], correctAnswer: 1, explanation: "Plural subject → are." },
    { id: "eng-25", question: "Antonym of 'begin'?", options: ["Start", "End", "Open", "Try"], correctAnswer: 1, explanation: "Begin ↔ end." },
    { id: "eng-26", question: "Which is a question word?", options: ["Run", "Where", "Tall", "And"], correctAnswer: 1, explanation: "'Where' asks a question." },
    { id: "eng-27", question: "Correct spelling:", options: ["Beleive", "Belive", "Believe", "Beleeve"], correctAnswer: 2, explanation: "Believe — i before e." },
    { id: "eng-28", question: "Identify the adjective: 'A red car.'", options: ["A", "Red", "Car", "None"], correctAnswer: 1, explanation: "'Red' describes the car." },
    { id: "eng-29", question: "Meaning of 'fragile'?", options: ["Strong", "Easily broken", "Heavy", "Bright"], correctAnswer: 1, explanation: "Fragile = easily broken." },
    { id: "eng-30", question: "Choose correct: 'He ___ to school every day.'", options: ["go", "goes", "going", "gone"], correctAnswer: 1, explanation: "Third-person singular → goes." },
    { id: "eng-31", question: "What is a metaphor?", options: ["Comparison with like/as", "Direct comparison", "Sound word", "Exaggeration"], correctAnswer: 1, explanation: "Metaphor compares directly." },
    { id: "eng-32", question: "Plural of 'leaf'?", options: ["Leafs", "Leaves", "Leafes", "Leave"], correctAnswer: 1, explanation: "Leaf → leaves." },
    { id: "eng-33", question: "Which is past perfect?", options: ["I eat", "I ate", "I had eaten", "I will eat"], correctAnswer: 2, explanation: "Had + past participle." },
    { id: "eng-34", question: "Antonym of 'ancient'?", options: ["Modern", "Old", "Tired", "Wise"], correctAnswer: 0, explanation: "Ancient ↔ modern." },
    { id: "eng-35", question: "Correct article: '___ apple a day.'", options: ["A", "An", "The", "No article"], correctAnswer: 1, explanation: "Vowel sound → an." },
    { id: "eng-36", question: "Meaning of 'eager'?", options: ["Tired", "Very keen", "Sad", "Angry"], correctAnswer: 1, explanation: "Eager = keen." },
    { id: "eng-37", question: "Which is a complete sentence?", options: ["Running fast.", "When the boy.", "She sings.", "Under the bed."], correctAnswer: 2, explanation: "Has subject + verb." },
    { id: "eng-38", question: "Plural of 'tooth'?", options: ["Tooths", "Teeths", "Teeth", "Tooth"], correctAnswer: 2, explanation: "Tooth → teeth." },
    { id: "eng-39", question: "Identify the interjection: 'Wow! That's great.'", options: ["Wow", "That's", "Great", "Is"], correctAnswer: 0, explanation: "'Wow!' expresses emotion." },
    { id: "eng-40", question: "Synonym of 'quick'?", options: ["Slow", "Fast", "Lazy", "Late"], correctAnswer: 1, explanation: "Quick = fast." },
  ],

  kiswahili: [
    { id: "kis-16", question: "Wingi wa 'jicho'?", options: ["majicho", "macho", "vicho", "vijicho"], correctAnswer: 1, explanation: "Jicho → macho." },
    { id: "kis-17", question: "Maana ya 'haraka'?", options: ["polepole", "kasi", "furaha", "huzuni"], correctAnswer: 1, explanation: "Haraka = kasi/speed." },
    { id: "kis-18", question: "Kinyume cha 'ndefu'?", options: ["fupi", "kubwa", "ndogo", "pana"], correctAnswer: 0, explanation: "Ndefu ↔ fupi." },
    { id: "kis-19", question: "Wingi wa 'mti'?", options: ["mitii", "miti", "mati", "wati"], correctAnswer: 1, explanation: "Mti → miti." },
    { id: "kis-20", question: "Wakati ujao wa 'kucheza':", options: ["nilicheza", "ninacheza", "nitacheza", "nimecheza"], correctAnswer: 2, explanation: "Nitacheza = ujao." },
    { id: "kis-21", question: "Aina ya neno 'kimbia':", options: ["nomino", "kitenzi", "kivumishi", "kielezi"], correctAnswer: 1, explanation: "Kimbia ni kitenzi." },
    { id: "kis-22", question: "Methali: 'Mchelea mwana kulia ___'", options: ["hulia mwenyewe", "huimba", "hucheka", "hulala"], correctAnswer: 0, explanation: "...hulia mwenyewe." },
    { id: "kis-23", question: "Kisawe cha 'haraka':", options: ["upesi", "polepole", "kimya", "uvivu"], correctAnswer: 0, explanation: "Haraka = upesi." },
    { id: "kis-24", question: "Wingi wa 'gari'?", options: ["magari", "vigari", "wagari", "migari"], correctAnswer: 0, explanation: "Gari → magari." },
    { id: "kis-25", question: "Maana ya 'asubuhi':", options: ["evening", "morning", "afternoon", "night"], correctAnswer: 1, explanation: "Asubuhi = morning." },
    { id: "kis-26", question: "Chagua nomino:", options: ["kula", "nyumba", "kubwa", "haraka"], correctAnswer: 1, explanation: "Nyumba ni nomino." },
    { id: "kis-27", question: "Rangi ya 'nyeusi' kwa Kiingereza:", options: ["white", "black", "blue", "green"], correctAnswer: 1, explanation: "Nyeusi = black." },
    { id: "kis-28", question: "Mwezi wa kwanza wa mwaka:", options: ["Februari", "Januari", "Machi", "Aprili"], correctAnswer: 1, explanation: "Januari." },
    { id: "kis-29", question: "Wingi wa 'ndugu':", options: ["wandugu", "ndugu", "vidugu", "mandugu"], correctAnswer: 1, explanation: "Ndugu (singular & plural same form)." },
    { id: "kis-30", question: "Maana ya 'kazi':", options: ["play", "work", "rest", "song"], correctAnswer: 1, explanation: "Kazi = work." },
  ],

  chemistry: [
    { id: "chem-16", question: "Symbol for Iron?", options: ["Ir", "I", "Fe", "Fr"], correctAnswer: 2, explanation: "Iron = Fe (Latin: ferrum)." },
    { id: "chem-17", question: "pH below 7 is?", options: ["Acidic", "Neutral", "Basic", "Salt"], correctAnswer: 0, explanation: "Acid: pH < 7." },
    { id: "chem-18", question: "Symbol for Gold?", options: ["Go", "Gd", "Au", "Ag"], correctAnswer: 2, explanation: "Gold = Au (aurum)." },
    { id: "chem-19", question: "Number of protons in Hydrogen?", options: ["0", "1", "2", "3"], correctAnswer: 1, explanation: "Atomic number 1." },
    { id: "chem-20", question: "Solid → gas directly is?", options: ["Melting", "Sublimation", "Freezing", "Boiling"], correctAnswer: 1, explanation: "Sublimation." },
    { id: "chem-21", question: "Formula of methane?", options: ["CH₄", "C₂H₆", "CO₂", "CH₃"], correctAnswer: 0, explanation: "Methane = CH₄." },
    { id: "chem-22", question: "Most reactive group of metals?", options: ["Noble gases", "Alkali metals", "Halogens", "Transition"], correctAnswer: 1, explanation: "Group 1 — alkali metals." },
    { id: "chem-23", question: "Symbol for Silver?", options: ["Si", "Sv", "Ag", "Au"], correctAnswer: 2, explanation: "Silver = Ag (argentum)." },
    { id: "chem-24", question: "Acid + base →?", options: ["Salt + water", "More acid", "Gas only", "Metal"], correctAnswer: 0, explanation: "Neutralisation: salt + water." },
    { id: "chem-25", question: "Process: gas → liquid?", options: ["Evaporation", "Condensation", "Melting", "Freezing"], correctAnswer: 1, explanation: "Condensation." },
    { id: "chem-26", question: "Common indicator for acids/bases?", options: ["Salt", "Litmus", "Sugar", "Oil"], correctAnswer: 1, explanation: "Litmus paper." },
    { id: "chem-27", question: "Number of natural elements (approx)?", options: ["50", "80", "94", "200"], correctAnswer: 2, explanation: "About 94 occur naturally." },
    { id: "chem-28", question: "Hardest known natural element form?", options: ["Iron", "Diamond (carbon)", "Lead", "Copper"], correctAnswer: 1, explanation: "Diamond (carbon)." },
    { id: "chem-29", question: "Universal solvent?", options: ["Oil", "Water", "Alcohol", "Acid"], correctAnswer: 1, explanation: "Water dissolves many substances." },
    { id: "chem-30", question: "Ozone formula?", options: ["O", "O₂", "O₃", "O₄"], correctAnswer: 2, explanation: "Ozone = O₃." },
  ],

  biology: [
    { id: "bio-16", question: "Energy currency of cells?", options: ["DNA", "ATP", "RNA", "Glucose"], correctAnswer: 1, explanation: "ATP." },
    { id: "bio-17", question: "Largest part of human brain?", options: ["Cerebellum", "Brainstem", "Cerebrum", "Medulla"], correctAnswer: 2, explanation: "Cerebrum." },
    { id: "bio-18", question: "Plants reproduce sexually via?", options: ["Leaves", "Flowers", "Roots", "Stem"], correctAnswer: 1, explanation: "Flowers." },
    { id: "bio-19", question: "Carnivore eats?", options: ["Plants only", "Meat", "Both", "Insects only"], correctAnswer: 1, explanation: "Meat eaters." },
    { id: "bio-20", question: "Insect with 3 body parts?", options: ["Spider", "Ant", "Crab", "Worm"], correctAnswer: 1, explanation: "Ants are insects (head, thorax, abdomen)." },
    { id: "bio-21", question: "Cell wall is found in?", options: ["Animal cells", "Plant cells", "Both", "Neither"], correctAnswer: 1, explanation: "Plant cells." },
    { id: "bio-22", question: "Oxygen is released during?", options: ["Respiration", "Photosynthesis", "Digestion", "Sleep"], correctAnswer: 1, explanation: "Photosynthesis." },
    { id: "bio-23", question: "Function of platelets?", options: ["Carry O₂", "Fight germs", "Clot blood", "Carry CO₂"], correctAnswer: 2, explanation: "Blood clotting." },
    { id: "bio-24", question: "Smallest blood vessel?", options: ["Artery", "Vein", "Capillary", "Aorta"], correctAnswer: 2, explanation: "Capillary." },
    { id: "bio-25", question: "Pollination by insects is?", options: ["Anemophily", "Entomophily", "Hydrophily", "Zoophily"], correctAnswer: 1, explanation: "Entomophily." },
    { id: "bio-26", question: "Joint at the elbow is?", options: ["Ball & socket", "Hinge", "Pivot", "Sliding"], correctAnswer: 1, explanation: "Hinge joint." },
    { id: "bio-27", question: "Excretory organ in skin?", options: ["Hair", "Sweat glands", "Nails", "Pores only"], correctAnswer: 1, explanation: "Sweat glands." },
    { id: "bio-28", question: "Frog is a?", options: ["Mammal", "Reptile", "Amphibian", "Fish"], correctAnswer: 2, explanation: "Amphibian." },
    { id: "bio-29", question: "Bacteria are?", options: ["Multi-cellular", "Single-celled", "Plants", "Viruses"], correctAnswer: 1, explanation: "Single-celled organisms." },
    { id: "bio-30", question: "Process by which roots take in water?", options: ["Diffusion", "Osmosis", "Active transport", "Respiration"], correctAnswer: 1, explanation: "Osmosis." },
  ],

  physics: [
    { id: "phy-16", question: "Unit of energy?", options: ["Newton", "Joule", "Watt", "Pascal"], correctAnswer: 1, explanation: "Joule." },
    { id: "phy-17", question: "Force = ?", options: ["mass × velocity", "mass × acceleration", "mass + speed", "mass ÷ acceleration"], correctAnswer: 1, explanation: "F = ma." },
    { id: "phy-18", question: "Frequency unit?", options: ["Hertz", "Joule", "Newton", "Ohm"], correctAnswer: 0, explanation: "Hertz (Hz)." },
    { id: "phy-19", question: "Echo is caused by?", options: ["Light", "Sound reflection", "Refraction", "Magnetism"], correctAnswer: 1, explanation: "Sound reflecting off surfaces." },
    { id: "phy-20", question: "Convex lens is also called?", options: ["Diverging", "Converging", "Flat", "Spherical only"], correctAnswer: 1, explanation: "Converging lens." },
    { id: "phy-21", question: "Unit of pressure?", options: ["Newton", "Pascal", "Watt", "Joule"], correctAnswer: 1, explanation: "Pascal (Pa)." },
    { id: "phy-22", question: "Object at rest stays at rest (law)?", options: ["1st", "2nd", "3rd", "Hooke's"], correctAnswer: 0, explanation: "Newton's 1st law (inertia)." },
    { id: "phy-23", question: "Voltage unit?", options: ["Ampere", "Ohm", "Volt", "Watt"], correctAnswer: 2, explanation: "Volt (V)." },
    { id: "phy-24", question: "Rainbow forms due to?", options: ["Reflection only", "Refraction & dispersion", "Magnetism", "Sound"], correctAnswer: 1, explanation: "Light splits via refraction/dispersion." },
    { id: "phy-25", question: "Best heat conductor?", options: ["Wood", "Plastic", "Copper", "Glass"], correctAnswer: 2, explanation: "Copper is a good conductor." },
    { id: "phy-26", question: "Pitch depends on?", options: ["Amplitude", "Frequency", "Speed", "Color"], correctAnswer: 1, explanation: "Higher frequency = higher pitch." },
    { id: "phy-27", question: "Friction can be reduced by?", options: ["Sand", "Lubrication", "Roughness", "Heat"], correctAnswer: 1, explanation: "Oils/grease reduce friction." },
    { id: "phy-28", question: "Earth's gravity pulls toward?", options: ["Sky", "Center of Earth", "Sun", "Moon"], correctAnswer: 1, explanation: "Toward Earth's center." },
    { id: "phy-29", question: "Speed = ?", options: ["Distance × time", "Distance ÷ time", "Time ÷ distance", "Mass × distance"], correctAnswer: 1, explanation: "Speed = distance/time." },
    { id: "phy-30", question: "Mirror that diverges light?", options: ["Plane", "Concave", "Convex", "Parabolic"], correctAnswer: 2, explanation: "Convex mirror diverges." },
  ],

  "general-science": [
    { id: "gs-16", question: "Sun is a?", options: ["Planet", "Star", "Moon", "Asteroid"], correctAnswer: 1, explanation: "Sun is a star." },
    { id: "gs-17", question: "Galaxy we live in?", options: ["Andromeda", "Milky Way", "Whirlpool", "Triangulum"], correctAnswer: 1, explanation: "Milky Way." },
    { id: "gs-18", question: "Number of teeth in adult humans?", options: ["28", "30", "32", "36"], correctAnswer: 2, explanation: "32 teeth." },
    { id: "gs-19", question: "Gas we exhale?", options: ["Oxygen", "Nitrogen", "Carbon dioxide", "Hydrogen"], correctAnswer: 2, explanation: "CO₂." },
    { id: "gs-20", question: "Force keeping us on Earth?", options: ["Magnetism", "Friction", "Gravity", "Wind"], correctAnswer: 2, explanation: "Gravity." },
    { id: "gs-21", question: "Speed of sound in air ≈?", options: ["100 m/s", "343 m/s", "1000 m/s", "3×10⁸ m/s"], correctAnswer: 1, explanation: "~343 m/s." },
    { id: "gs-22", question: "Vitamin C source?", options: ["Meat", "Oranges", "Milk", "Bread"], correctAnswer: 1, explanation: "Citrus fruits." },
    { id: "gs-23", question: "Smallest planet?", options: ["Mars", "Mercury", "Venus", "Pluto"], correctAnswer: 1, explanation: "Mercury (Pluto is dwarf)." },
    { id: "gs-24", question: "Earth rotates in (hours):", options: ["12", "18", "24", "30"], correctAnswer: 2, explanation: "24 hours." },
    { id: "gs-25", question: "Most abundant element in universe?", options: ["Oxygen", "Hydrogen", "Carbon", "Iron"], correctAnswer: 1, explanation: "Hydrogen." },
    { id: "gs-26", question: "Largest mammal?", options: ["Elephant", "Blue whale", "Giraffe", "Hippo"], correctAnswer: 1, explanation: "Blue whale." },
    { id: "gs-27", question: "Sense organ for smell?", options: ["Tongue", "Nose", "Eye", "Ear"], correctAnswer: 1, explanation: "Nose." },
    { id: "gs-28", question: "Light year measures?", options: ["Time", "Distance", "Speed", "Mass"], correctAnswer: 1, explanation: "Distance light travels in 1 year." },
    { id: "gs-29", question: "Most common blood type?", options: ["A", "B", "AB", "O"], correctAnswer: 3, explanation: "Type O." },
    { id: "gs-30", question: "Layer that protects from UV?", options: ["Crust", "Ozone", "Mantle", "Crust"], correctAnswer: 1, explanation: "Ozone layer." },
  ],

  "computer-studies": [
    { id: "cs-16", question: "USB stands for?", options: ["Universal Serial Bus", "United System Bus", "Universal Save Bus", "User Serial Box"], correctAnswer: 0, explanation: "Universal Serial Bus." },
    { id: "cs-17", question: "Binary of 8?", options: ["100", "101", "1000", "1010"], correctAnswer: 2, explanation: "8 = 1000." },
    { id: "cs-18", question: "GUI stands for?", options: ["General User Interface", "Graphical User Interface", "Grand User Input", "Global User Index"], correctAnswer: 1, explanation: "Graphical User Interface." },
    { id: "cs-19", question: "Software for word processing?", options: ["Excel", "Word", "PowerPoint", "Access"], correctAnswer: 1, explanation: "MS Word." },
    { id: "cs-20", question: "URL stands for?", options: ["Uniform Resource Locator", "Universal Reference Link", "User Routing Link", "Uniform Routing List"], correctAnswer: 0, explanation: "Uniform Resource Locator." },
    { id: "cs-21", question: "Shortcut to save?", options: ["Ctrl+S", "Ctrl+P", "Ctrl+O", "Ctrl+N"], correctAnswer: 0, explanation: "Ctrl+S saves." },
    { id: "cs-22", question: "1 KB = ?", options: ["100 bytes", "1024 bytes", "1000 KB", "1 MB"], correctAnswer: 1, explanation: "1024 bytes." },
    { id: "cs-23", question: "Pointing device?", options: ["Keyboard", "Mouse", "Monitor", "Printer"], correctAnswer: 1, explanation: "Mouse." },
    { id: "cs-24", question: "Volatile memory?", options: ["ROM", "RAM", "HDD", "SSD"], correctAnswer: 1, explanation: "RAM loses data when powered off." },
    { id: "cs-25", question: "Language used to query databases?", options: ["HTML", "SQL", "CSS", "JS"], correctAnswer: 1, explanation: "SQL." },
    { id: "cs-26", question: "Antivirus protects against?", options: ["Heat", "Malware", "Power surges", "Dust"], correctAnswer: 1, explanation: "Viruses/malware." },
    { id: "cs-27", question: "Spreadsheet software?", options: ["Word", "Excel", "Photoshop", "Outlook"], correctAnswer: 1, explanation: "Excel." },
    { id: "cs-28", question: "AI stands for?", options: ["Auto Internet", "Artificial Intelligence", "Active Input", "Applied Index"], correctAnswer: 1, explanation: "Artificial Intelligence." },
    { id: "cs-29", question: "File compressed using?", options: [".txt", ".zip", ".doc", ".jpg"], correctAnswer: 1, explanation: ".zip files compress." },
    { id: "cs-30", question: "Smallest binary unit?", options: ["Byte", "Bit", "Nibble", "Word"], correctAnswer: 1, explanation: "Bit." },
  ],

  literature: [
    { id: "lit-16", question: "Shakespeare wrote?", options: ["Hamlet", "Iliad", "Odyssey", "Aeneid"], correctAnswer: 0, explanation: "Hamlet is by Shakespeare." },
    { id: "lit-17", question: "Author of 'River and the Source'?", options: ["Margaret Ogola", "Achebe", "Ngugi", "Soyinka"], correctAnswer: 0, explanation: "Margaret Ogola." },
    { id: "lit-18", question: "A short, witty poem?", options: ["Epic", "Epigram", "Ode", "Ballad"], correctAnswer: 1, explanation: "Epigram." },
    { id: "lit-19", question: "Character opposing the hero?", options: ["Protagonist", "Antagonist", "Narrator", "Sidekick"], correctAnswer: 1, explanation: "Antagonist." },
    { id: "lit-20", question: "A long narrative poem?", options: ["Haiku", "Epic", "Sonnet", "Limerick"], correctAnswer: 1, explanation: "Epic." },
    { id: "lit-21", question: "Atmosphere of a story?", options: ["Plot", "Mood", "Theme", "Style"], correctAnswer: 1, explanation: "Mood." },
    { id: "lit-22", question: "Comparing using 'as' is a?", options: ["Metaphor", "Simile", "Hyperbole", "Symbol"], correctAnswer: 1, explanation: "Simile uses 'as'." },
    { id: "lit-23", question: "Form of drama meant to be funny?", options: ["Tragedy", "Comedy", "Epic", "Sonnet"], correctAnswer: 1, explanation: "Comedy." },
    { id: "lit-24", question: "Author of 'The River Between'?", options: ["Achebe", "Ngugi wa Thiong'o", "Soyinka", "Ogola"], correctAnswer: 1, explanation: "Ngugi wa Thiong'o." },
    { id: "lit-25", question: "Hint about future events?", options: ["Flashback", "Foreshadowing", "Climax", "Irony"], correctAnswer: 1, explanation: "Foreshadowing." },
    { id: "lit-26", question: "A speech by one character alone?", options: ["Dialogue", "Soliloquy", "Chorus", "Aside"], correctAnswer: 1, explanation: "Soliloquy." },
    { id: "lit-27", question: "Most exciting point in a story?", options: ["Setting", "Climax", "Exposition", "Resolution"], correctAnswer: 1, explanation: "Climax." },
    { id: "lit-28", question: "First-person narrator uses?", options: ["He/She", "I/We", "You", "They"], correctAnswer: 1, explanation: "I/we." },
  ],

  business: [
    { id: "bus-16", question: "Liabilities are?", options: ["What you own", "What you owe", "Income", "Profit"], correctAnswer: 1, explanation: "Liabilities = debts." },
    { id: "bus-17", question: "Assets are?", options: ["Debts", "Things owned", "Expenses", "Tax"], correctAnswer: 1, explanation: "Things of value owned." },
    { id: "bus-18", question: "Wholesaler sells to?", options: ["Consumers", "Retailers", "Farmers only", "Government only"], correctAnswer: 1, explanation: "Retailers in bulk." },
    { id: "bus-19", question: "Supply increases when price...?", options: ["Falls", "Rises", "Stays", "Disappears"], correctAnswer: 1, explanation: "Law of supply." },
    { id: "bus-20", question: "Inflation is?", options: ["Falling prices", "Rising prices", "Stable prices", "No prices"], correctAnswer: 1, explanation: "General rise in prices." },
    { id: "bus-21", question: "Document requesting goods?", options: ["Receipt", "Invoice", "Order", "Cheque"], correctAnswer: 2, explanation: "Order form." },
    { id: "bus-22", question: "Person who buys goods?", options: ["Seller", "Customer", "Supplier", "Worker"], correctAnswer: 1, explanation: "Customer/consumer." },
    { id: "bus-23", question: "Barter trade is?", options: ["Cash trade", "Exchange of goods", "Online trade", "Tax"], correctAnswer: 1, explanation: "Goods for goods." },
    { id: "bus-24", question: "M-Pesa is a?", options: ["Bank", "Mobile money", "Stock", "Loan"], correctAnswer: 1, explanation: "Mobile money service." },
    { id: "bus-25", question: "SACCO stands for?", options: ["Savings & Credit Cooperative", "Sales Co.", "State Account Co.", "Savings Auction Co."], correctAnswer: 0, explanation: "Savings & Credit Cooperative." },
    { id: "bus-26", question: "Marketing aims to?", options: ["Hide products", "Promote products", "Tax products", "Destroy stock"], correctAnswer: 1, explanation: "Promote/sell." },
    { id: "bus-27", question: "Currency exchange rate is?", options: ["Tax rate", "Value of one currency in another", "Interest", "Profit"], correctAnswer: 1, explanation: "Relative value." },
  ],

  "social-studies": [
    { id: "ss-16", question: "Kenya's national anthem language?", options: ["English only", "Kiswahili", "Both", "French"], correctAnswer: 2, explanation: "Kiswahili and English." },
    { id: "ss-17", question: "Second largest city in Kenya?", options: ["Kisumu", "Mombasa", "Eldoret", "Nakuru"], correctAnswer: 1, explanation: "Mombasa." },
    { id: "ss-18", question: "Kenya's parliament has how many houses?", options: ["1", "2", "3", "4"], correctAnswer: 1, explanation: "National Assembly + Senate." },
    { id: "ss-19", question: "EAC member NOT in Kenya?", options: ["Uganda", "Tanzania", "Rwanda", "Egypt"], correctAnswer: 3, explanation: "Egypt is not in EAC." },
    { id: "ss-20", question: "Kenya's largest national park?", options: ["Tsavo", "Nairobi NP", "Amboseli", "Mt. Kenya"], correctAnswer: 0, explanation: "Tsavo (East+West)." },
    { id: "ss-21", question: "Kenya's coat of arms shows?", options: ["Two lions", "Two eagles", "Two cows", "Two dogs"], correctAnswer: 0, explanation: "Two lions holding spears." },
    { id: "ss-22", question: "Mau Mau fought against?", options: ["Germans", "British rule", "French", "Italians"], correctAnswer: 1, explanation: "British colonial rule." },
    { id: "ss-23", question: "Kenya borders which ocean?", options: ["Atlantic", "Pacific", "Indian", "Arctic"], correctAnswer: 2, explanation: "Indian Ocean." },
    { id: "ss-24", question: "Number of stripes on Kenya flag?", options: ["3", "4", "5", "6"], correctAnswer: 1, explanation: "Black, red, green + 2 white = 4 main stripes (with white fimbriations)." },
    { id: "ss-25", question: "Kenya National Assembly seats (elected MPs)?", options: ["210", "290", "300", "349"], correctAnswer: 1, explanation: "290 constituencies." },
    { id: "ss-26", question: "First female VP nominee in Kenya?", options: ["Charity Ngilu", "Martha Karua", "Rachel Ruto", "Phoebe Asiyo"], correctAnswer: 1, explanation: "Martha Karua (2022)." },
    { id: "ss-27", question: "Devolved government in Kenya started?", options: ["2010", "2013", "2017", "2022"], correctAnswer: 1, explanation: "2013 after 2010 Constitution." },
  ],

  "creative-arts": [
    { id: "ca-11", question: "Color wheel was created by?", options: ["Newton", "Picasso", "Da Vinci", "Monet"], correctAnswer: 0, explanation: "Isaac Newton." },
    { id: "ca-12", question: "Mixing blue + yellow makes?", options: ["Orange", "Green", "Purple", "Brown"], correctAnswer: 1, explanation: "Green." },
    { id: "ca-13", question: "Type of music with no words?", options: ["Vocal", "Instrumental", "Choir", "Opera"], correctAnswer: 1, explanation: "Instrumental." },
    { id: "ca-14", question: "Drama performed with movement only?", options: ["Mime", "Opera", "Recital", "Lecture"], correctAnswer: 0, explanation: "Mime." },
    { id: "ca-15", question: "Used to mold clay?", options: ["Hands", "Hammer", "Saw", "Pencil"], correctAnswer: 0, explanation: "Hands/tools." },
    { id: "ca-16", question: "Beat in music is?", options: ["Color", "Pulse/rhythm", "Pitch", "Tone"], correctAnswer: 1, explanation: "Steady pulse." },
    { id: "ca-17", question: "Weaving produces?", options: ["Painting", "Fabric", "Sculpture", "Drawing"], correctAnswer: 1, explanation: "Cloth/fabric." },
    { id: "ca-18", question: "Cool colors include?", options: ["Red, orange", "Blue, green", "Yellow, red", "Pink"], correctAnswer: 1, explanation: "Blue and green." },
  ],

  agriculture: [
    { id: "agri-13", question: "Sheep give us?", options: ["Milk only", "Wool & meat", "Eggs", "Honey"], correctAnswer: 1, explanation: "Wool and meat." },
    { id: "agri-14", question: "Plowing prepares?", options: ["Roof", "Land", "Pond", "Air"], correctAnswer: 1, explanation: "Land for planting." },
    { id: "agri-15", question: "Free-range farming means?", options: ["Caged", "Roaming freely", "Indoor only", "Underwater"], correctAnswer: 1, explanation: "Animals roam freely." },
    { id: "agri-16", question: "Best season to plant maize in Kenya?", options: ["Dry", "Rainy", "Cold", "Windy"], correctAnswer: 1, explanation: "Long rains." },
    { id: "agri-17", question: "Source of organic manure?", options: ["Plastic", "Animal waste", "Metal", "Stones"], correctAnswer: 1, explanation: "Animal dung." },
    { id: "agri-18", question: "Tea grows best in?", options: ["Hot lowlands", "Cool highlands", "Deserts", "Swamps"], correctAnswer: 1, explanation: "Cool highlands." },
    { id: "agri-19", question: "Aquaculture is?", options: ["Tree farming", "Fish farming", "Cattle farming", "Bird farming"], correctAnswer: 1, explanation: "Fish farming." },
    { id: "agri-20", question: "Tractor is a?", options: ["Hand tool", "Farm machine", "Crop", "Fertilizer"], correctAnswer: 1, explanation: "Mechanized equipment." },
  ],

  "integrated-science": [
    { id: "is-13", question: "Photosynthesis happens in?", options: ["Roots", "Leaves", "Stem", "Flowers only"], correctAnswer: 1, explanation: "Mainly in leaves (chloroplasts)." },
    { id: "is-14", question: "Magnet poles that repel?", options: ["N & S", "N & N", "S & N", "None"], correctAnswer: 1, explanation: "Like poles repel." },
    { id: "is-15", question: "Mixture of metals?", options: ["Alloy", "Compound", "Solution", "Element"], correctAnswer: 0, explanation: "Alloy." },
    { id: "is-16", question: "Sound waves are?", options: ["Transverse", "Longitudinal", "Static", "Electromagnetic"], correctAnswer: 1, explanation: "Longitudinal waves." },
    { id: "is-17", question: "Number of bones a baby is born with?", options: ["206", "270", "300", "150"], correctAnswer: 2, explanation: "~300, fuse to 206 in adults." },
    { id: "is-18", question: "Water cycle stage when vapor rises?", options: ["Evaporation", "Condensation", "Precipitation", "Runoff"], correctAnswer: 0, explanation: "Evaporation." },
    { id: "is-19", question: "Renewable resource?", options: ["Coal", "Oil", "Wind", "Gas"], correctAnswer: 2, explanation: "Wind energy." },
    { id: "is-20", question: "Acid found in lemons?", options: ["HCl", "Citric acid", "Sulfuric", "Lactic"], correctAnswer: 1, explanation: "Citric acid." },
  ],

  "pre-technical": [
    { id: "pt-11", question: "Spanner is used for?", options: ["Cutting", "Tightening bolts", "Drilling", "Painting"], correctAnswer: 1, explanation: "Bolts and nuts." },
    { id: "pt-12", question: "Pulley is a simple?", options: ["Lever", "Machine", "Inclined plane", "Wedge"], correctAnswer: 1, explanation: "Simple machine." },
    { id: "pt-13", question: "Wedge example?", options: ["Wheel", "Axe", "Pulley", "Screw"], correctAnswer: 1, explanation: "Axe is a wedge." },
    { id: "pt-14", question: "Bulb converts electricity to?", options: ["Sound", "Light", "Magnetism", "Motion"], correctAnswer: 1, explanation: "Light energy." },
    { id: "pt-15", question: "Switch controls?", options: ["Heat", "Electric flow", "Sound", "Water"], correctAnswer: 1, explanation: "Opens/closes circuit." },
    { id: "pt-16", question: "Solar panel converts?", options: ["Sound to heat", "Sunlight to electricity", "Wind to heat", "Water to gas"], correctAnswer: 1, explanation: "Sunlight → electricity." },
    { id: "pt-17", question: "Workshop fire safety tool?", options: ["Hammer", "Extinguisher", "Saw", "Plane"], correctAnswer: 1, explanation: "Fire extinguisher." },
    { id: "pt-18", question: "Carpentry tool for smoothing wood?", options: ["Plane", "Hammer", "Drill", "File"], correctAnswer: 0, explanation: "Wood plane." },
  ],

  pe: [
    { id: "pe-11", question: "Number of players in volleyball team (court)?", options: ["5", "6", "7", "9"], correctAnswer: 1, explanation: "6 on court." },
    { id: "pe-12", question: "Sport with rings, bars and beams?", options: ["Boxing", "Gymnastics", "Soccer", "Wrestling"], correctAnswer: 1, explanation: "Gymnastics." },
    { id: "pe-13", question: "Number of players on a basketball team (court)?", options: ["4", "5", "6", "7"], correctAnswer: 1, explanation: "5 players." },
    { id: "pe-14", question: "100m sprint is a?", options: ["Field event", "Track event", "Water sport", "Combat"], correctAnswer: 1, explanation: "Track event." },
    { id: "pe-15", question: "Stretching improves?", options: ["Strength", "Flexibility", "Speed only", "Power only"], correctAnswer: 1, explanation: "Flexibility." },
    { id: "pe-16", question: "Penalty kick in soccer is from?", options: ["6 m", "9 m", "11 m", "18 m"], correctAnswer: 2, explanation: "11 metres (12 yards)." },
    { id: "pe-17", question: "Goal of soccer?", options: ["Shoot ball into goal", "Hit other team", "Hold ball longest", "Run fastest"], correctAnswer: 0, explanation: "Score in opponent's goal." },
    { id: "pe-18", question: "Olympics 2024 host?", options: ["Tokyo", "Paris", "London", "Rio"], correctAnswer: 1, explanation: "Paris 2024." },
  ],

  ict: [
    { id: "ict-11", question: "Two-factor authentication adds?", options: ["A weakness", "Extra security", "More storage", "Speed"], correctAnswer: 1, explanation: "Extra layer of security." },
    { id: "ict-12", question: "Phishing is?", options: ["Catching fish", "Fake messages stealing info", "An OS", "A browser"], correctAnswer: 1, explanation: "Online scam to steal info." },
    { id: "ict-13", question: "Wi-Fi is?", options: ["Wired only", "Wireless network", "Game", "Database"], correctAnswer: 1, explanation: "Wireless internet." },
    { id: "ict-14", question: "Spam is?", options: ["Food only", "Unwanted bulk messages", "An app", "A virus only"], correctAnswer: 1, explanation: "Unwanted emails/messages." },
    { id: "ict-15", question: "Backup means?", options: ["Delete files", "Copy files safely", "Open files", "Print files"], correctAnswer: 1, explanation: "Save a copy elsewhere." },
    { id: "ict-16", question: "Software piracy is?", options: ["Legal", "Illegal copying of software", "Updating", "Installing"], correctAnswer: 1, explanation: "Illegal duplication." },
    { id: "ict-17", question: "GIF is a?", options: ["Video", "Image format", "Sound", "Text"], correctAnswer: 1, explanation: "Image (often animated)." },
    { id: "ict-18", question: "Open-source software example?", options: ["Windows", "Linux", "MacOS", "iOS"], correctAnswer: 1, explanation: "Linux is open source." },
    { id: "ict-19", question: "Best password example?", options: ["1234", "password", "Tr0ub4!Stud", "abc"], correctAnswer: 2, explanation: "Mix of letters, digits, symbols." },
    { id: "ict-20", question: "ISP stands for?", options: ["Internet Service Provider", "Internal System Path", "Internet Security Plan", "Internal Source Page"], correctAnswer: 0, explanation: "Internet Service Provider." },
  ],

  history: [
    { id: "his-11", question: "First man on the Moon (year)?", options: ["1965", "1969", "1971", "1975"], correctAnswer: 1, explanation: "1969 (Apollo 11)." },
    { id: "his-12", question: "Slave trade abolished in British Empire (year)?", options: ["1807", "1833", "1865", "1900"], correctAnswer: 0, explanation: "Slave Trade Act 1807." },
    { id: "his-13", question: "Kenya colonial capital before Nairobi?", options: ["Kisumu", "Machakos", "Mombasa", "Nakuru"], correctAnswer: 2, explanation: "Mombasa." },
    { id: "his-14", question: "World War I started in?", options: ["1910", "1914", "1918", "1920"], correctAnswer: 1, explanation: "1914." },
    { id: "his-15", question: "Kenya's 4th president?", options: ["Moi", "Kibaki", "Uhuru", "Ruto"], correctAnswer: 2, explanation: "Uhuru Kenyatta." },
    { id: "his-16", question: "Kenya's 5th president?", options: ["Uhuru", "Raila", "Ruto", "Kibaki"], correctAnswer: 2, explanation: "William Ruto (2022)." },
    { id: "his-17", question: "Ancient Egyptian rulers were called?", options: ["Kings", "Pharaohs", "Sultans", "Emperors"], correctAnswer: 1, explanation: "Pharaohs." },
    { id: "his-18", question: "Cold War was between?", options: ["UK & France", "USA & USSR", "China & Japan", "India & Pakistan"], correctAnswer: 1, explanation: "USA and Soviet Union." },
  ],

  geography: [
    { id: "geo-11", question: "Largest country by area?", options: ["USA", "Canada", "Russia", "China"], correctAnswer: 2, explanation: "Russia." },
    { id: "geo-12", question: "Continent with most countries?", options: ["Asia", "Europe", "Africa", "Americas"], correctAnswer: 2, explanation: "Africa (54)." },
    { id: "geo-13", question: "Sahara is in which continent?", options: ["Asia", "Africa", "Australia", "Americas"], correctAnswer: 1, explanation: "Africa." },
    { id: "geo-14", question: "Highest mountain on Earth?", options: ["K2", "Everest", "Kilimanjaro", "Aconcagua"], correctAnswer: 1, explanation: "Mt. Everest." },
    { id: "geo-15", question: "Longest river in world?", options: ["Amazon", "Nile", "Yangtze", "Congo"], correctAnswer: 1, explanation: "Nile (commonly cited)." },
    { id: "geo-16", question: "Country with most population?", options: ["USA", "India", "China", "Brazil"], correctAnswer: 1, explanation: "India (since 2023)." },
    { id: "geo-17", question: "Capital of Tanzania?", options: ["Dar es Salaam", "Dodoma", "Arusha", "Mwanza"], correctAnswer: 1, explanation: "Dodoma is official capital." },
    { id: "geo-18", question: "Capital of Uganda?", options: ["Kampala", "Entebbe", "Jinja", "Gulu"], correctAnswer: 0, explanation: "Kampala." },
  ],

  "religious-ed": [
    { id: "re-11", question: "Christian holy day?", options: ["Friday", "Saturday", "Sunday", "Monday"], correctAnswer: 2, explanation: "Sunday." },
    { id: "re-12", question: "Number of Apostles of Jesus?", options: ["10", "12", "14", "7"], correctAnswer: 1, explanation: "Twelve apostles." },
    { id: "re-13", question: "Pilgrimage to Mecca is?", options: ["Salah", "Hajj", "Zakat", "Sawm"], correctAnswer: 1, explanation: "Hajj." },
    { id: "re-14", question: "Fasting month in Islam?", options: ["Shaban", "Ramadan", "Muharram", "Rajab"], correctAnswer: 1, explanation: "Ramadan." },
    { id: "re-15", question: "Founder of Christianity?", options: ["Moses", "Jesus Christ", "Paul", "Peter"], correctAnswer: 1, explanation: "Jesus Christ." },
    { id: "re-16", question: "Founder of Islam?", options: ["Jesus", "Prophet Muhammad", "Abraham", "Moses"], correctAnswer: 1, explanation: "Prophet Muhammad (PBUH)." },
    { id: "re-17", question: "Hindu holy book?", options: ["Quran", "Bible", "Bhagavad Gita", "Torah"], correctAnswer: 2, explanation: "Bhagavad Gita (among others)." },
    { id: "re-18", question: "Forgiveness means?", options: ["Holding a grudge", "Pardoning a wrong", "Revenge", "Ignoring"], correctAnswer: 1, explanation: "Letting go of wrongs." },
  ],

  csl: [
    { id: "csl-9", question: "Honesty is?", options: ["Lying", "Telling the truth", "Hiding", "Cheating"], correctAnswer: 1, explanation: "Truthfulness." },
    { id: "csl-10", question: "A community is?", options: ["A person", "A group of people sharing area/interests", "An app", "A school"], correctAnswer: 1, explanation: "Group living/working together." },
    { id: "csl-11", question: "Why pay taxes?", options: ["For fun", "To fund public services", "To lose money", "No reason"], correctAnswer: 1, explanation: "Fund public services." },
    { id: "csl-12", question: "Conflict resolution is?", options: ["Fighting more", "Solving disputes peacefully", "Avoiding people", "Yelling"], correctAnswer: 1, explanation: "Peaceful solutions." },
    { id: "csl-13", question: "Diversity means?", options: ["All same", "Different cultures/people", "One race", "One language"], correctAnswer: 1, explanation: "Variety of people/cultures." },
    { id: "csl-14", question: "Leadership requires?", options: ["Shouting", "Responsibility & integrity", "Power abuse", "Selfishness"], correctAnswer: 1, explanation: "Responsibility & integrity." },
  ],

  "sports-science": [
    { id: "sps-9", question: "Muscle that bends a joint?", options: ["Extensor", "Flexor", "Tendon", "Ligament"], correctAnswer: 1, explanation: "Flexor bends." },
    { id: "sps-10", question: "Hormone for stress response?", options: ["Insulin", "Adrenaline", "Thyroxine", "Estrogen"], correctAnswer: 1, explanation: "Adrenaline." },
    { id: "sps-11", question: "RICE in injury treatment?", options: ["Rice food", "Rest, Ice, Compress, Elevate", "Run, Ice, Carry, Eat", "Rest, Insulin, Calm, Eat"], correctAnswer: 1, explanation: "Rest, Ice, Compression, Elevation." },
    { id: "sps-12", question: "Heart rate measured in?", options: ["BPM", "Hz", "kg", "cm"], correctAnswer: 0, explanation: "Beats per minute." },
    { id: "sps-13", question: "Carbs provide?", options: ["Building blocks", "Energy", "Vitamins", "Minerals"], correctAnswer: 1, explanation: "Main energy source." },
    { id: "sps-14", question: "Dehydration causes?", options: ["Strength", "Fatigue & cramps", "Speed", "Better performance"], correctAnswer: 1, explanation: "Fatigue, cramps, poor performance." },
  ],

  "fine-art": [
    { id: "fa-9", question: "Picasso founded which art movement?", options: ["Impressionism", "Cubism", "Realism", "Pop art"], correctAnswer: 1, explanation: "Cubism (with Braque)." },
    { id: "fa-10", question: "Van Gogh's famous painting?", options: ["Mona Lisa", "Starry Night", "The Scream", "Guernica"], correctAnswer: 1, explanation: "Starry Night." },
    { id: "fa-11", question: "Watercolor uses?", options: ["Oil base", "Water base", "Wax", "Clay"], correctAnswer: 1, explanation: "Water-based pigment." },
    { id: "fa-12", question: "Composition in art is?", options: ["Music writing", "Arrangement of elements", "Color mixing", "Frame size"], correctAnswer: 1, explanation: "How elements are placed." },
    { id: "fa-13", question: "Pottery is made from?", options: ["Iron", "Clay", "Glass", "Plastic"], correctAnswer: 1, explanation: "Clay fired in kiln." },
    { id: "fa-14", question: "Warm color?", options: ["Blue", "Red", "Green", "Purple"], correctAnswer: 1, explanation: "Red is warm." },
  ],

  music: [
    { id: "mus-9", question: "Treble clef is for?", options: ["Low notes", "High notes", "No notes", "Drums"], correctAnswer: 1, explanation: "Higher pitched notes." },
    { id: "mus-10", question: "Bass clef is for?", options: ["Low notes", "High notes", "Lyrics", "Chords"], correctAnswer: 0, explanation: "Lower pitched notes." },
    { id: "mus-11", question: "Rhythm is?", options: ["Color of sound", "Pattern of beats", "Loudness", "Lyrics"], correctAnswer: 1, explanation: "Pattern of beats." },
    { id: "mus-12", question: "Choir is a group that?", options: ["Plays drums", "Sings together", "Dances", "Acts"], correctAnswer: 1, explanation: "Group of singers." },
    { id: "mus-13", question: "Symbol for silence in music?", options: ["Note", "Rest", "Sharp", "Flat"], correctAnswer: 1, explanation: "Rest." },
    { id: "mus-14", question: "Piano is what kind of instrument?", options: ["Wind", "String/Keyboard", "Percussion only", "Brass"], correctAnswer: 1, explanation: "Keyboard with strings struck by hammers." },
  ],
};

export default extraQuestions;
